Dev ex02 totaisei
dai65527/pokedex_vue pull request #11
Opened 2021-01-18 13:00 UTC by ToYeah

2021-01-19 02:35 UTC, dai65527 requested changes
確認しました。さすが、って感じです。
一部修正をお願いしてもいいですか？
相談するところは、ボイチャなどで話しましょう！

- v-for化やコンポーネント化できるところがありそうです。コードの見通しと拡張性が上がりそうなところに関してはコンポーネント化してみてください！
- 幅いっぱいにポケモンの画像が表示されて見づらいかもしれないと思いました。max-widthを指定できればした方がよいと思います。

2021-01-19 02:35 UTC, dai65527 commented on ex02/pokedex/src/components/NavBar.vue
> +        <router-link :to="{ name: 'pokedex' }">
入れようと思ってました！ありがとうございます！

2021-01-19 02:35 UTC, dai65527 commented on ex02/pokedex/src/components/PokeBallSpinner.vue
> +}
CSSマスター...！！

2021-01-19 02:35 UTC, dai65527 commented on ex02/pokedex/src/components/Pokemon.vue
> +                  />
- poke-info-textに出す情報を配列化してv-forで回した方が拡張性高そうに思います。
- typesに関しては先に文字列を作ってそれを渡す方がいいかもですね。（computed property）でできそうです。
- ここはまとめてコンポーネント化したらすっきりしそうですね。

2021-01-19 02:35 UTC, dai65527 commented on ex02/pokedex/src/components/Pokemon.vue
> +                  <pokechart :pokeStats="pokeInfo.stats"></pokechart>
ここもコンポーネント化したらすっきりしそうですね。

2021-01-19 02:35 UTC, dai65527 commented on ex02/pokedex/src/components/Pokemon.vue
> +          <v-col cols="12" lg="6" class="my-auto">
lg 以下だとブラウザの幅いっぱいにポケモンの画像が出て表示が少し見にくい場合があるように感じました。
max-widthの指定をして改善できないですかね？

2021-01-19 02:35 UTC, dai65527 commented on ex02/pokedex/src/components/Pokemon.vue
> +    <poke-ball-spinner v-if="!flgFetched"></poke-ball-spinner>
最高です！！！！！

2021-01-19 02:35 UTC, dai65527 commented on ex02/pokedex/src/components/Pokemon.vue
> +    <poke-ball-spinner v-if="!flgFetched"></poke-ball-spinner>
ただ、課題文に読み込み中は"Loading..."と出力するよう指定があるので、ボールの横か下に小さく追加しておきますか？笑

2021-01-19 02:35 UTC, dai65527 commented on ex02/pokedex/src/components/Pokemon.vue
>    private messageNotLoaded = "Loading...";
読み込み失敗時はaxiosErrorを入れておくこの文字列を表示する必要があります。

2021-01-19 02:35 UTC, dai65527 commented on ex02/pokedex/src/models/pokeInfo.ts
> +    resPokeInfo.data.height / 10,
修正ありがとうございました！

2021-01-19 02:35 UTC, dai65527 commented on ex02/pokedex/src/components/Pokechart.vue
> +import { Radar, mixins } from "vue-chartjs";
　こんなのがあるんですねえ！

2021-01-20 16:22 UTC, ToYeah commented on ex02/pokedex/src/components/Pokemon.vue
> +                  />
PokeCardInfoコンポーネントでラップしました！

2021-01-20 16:24 UTC, ToYeah commented on ex02/pokedex/src/components/Pokemon.vue
> +                  <pokechart :pokeStats="pokeInfo.stats"></pokechart>
RadarChartコンポーネントに移動した後Pokechartコンポーネントで呼び出す形にしました。

2021-01-20 16:24 UTC, ToYeah commented on ex02/pokedex/src/components/Pokemon.vue
> +          <v-col cols="12" lg="6" class="my-auto">
開発するときずっと50%の広さで見てました笑
100%にしたらなにもかもデカかったので収まるようmax-widthの設定等を行いました

2021-01-20 16:25 UTC, ToYeah commented on ex02/pokedex/src/components/Pokemon.vue
> +    <poke-ball-spinner v-if="!flgFetched"></poke-ball-spinner>
Spinnerに文字列をバインドして表示されるようにしました！

2021-01-21 13:16 UTC, dai65527 reviewed
UIがさらに美しくなってて素晴らしいです！細かいところコメントしたので少し修正願います！

2021-01-21 13:16 UTC, dai65527 commented on ex02/pokedex/src/components/PokeBallSpinner.vue
> +          <p class="mx-auto grey--text text--lighten-1 display-1 text text-center">
オートフォーマットで改行しましょ。

2021-01-21 13:16 UTC, dai65527 commented on ex02/pokedex/src/components/PokeChart.vue
> +    <v-spacer/>
フォーマットエラーあるっぽいのでフォーマッタ通しましょ

2021-01-21 13:16 UTC, dai65527 commented on ex02/pokedex/src/components/PokeInfoCard.vue
> +  private informations: { title: string; value: string | number }[] = [];
TSっぽい！（知らんけど）

2021-01-21 13:16 UTC, dai65527 commented on ex02/pokedex/src/components/PokeList.vue
> +    <v-container fluid>
こう使えばいいんすねー

2021-01-21 13:16 UTC, dai65527 commented on ex02/pokedex/src/components/PokeList.vue
> +<style>
style scopedにした方が良いかと思います！（他のコンポーネントに影響しなくなります）

2021-01-21 13:16 UTC, dai65527 commented on ex02/pokedex/src/components/Pokemon.vue
> +import PokeChart from "@/components/PokeChart.vue";
import不要かと思います。（ここでこのコンポーネントは呼んでませんね）

2021-01-21 13:16 UTC, dai65527 commented on ex02/pokedex/src/components/PokeBallSpinner.vue
> +            {{infoText}}
フォーマッタにしたがって`{{ infoText }}`にしましょ。

2021-01-21 13:16 UTC, dai65527 commented on ex02/pokedex/src/components/Pokemon.vue
> +<style>
scoped入れた方が良いかと！

2021-01-21 13:16 UTC, dai65527 commented on ex02/pokedex/src/components/Pokemon.vue
> +  width: 100%;
vuetifyで指定できるやつはしましょうか！

2021-01-21 13:16 UTC, dai65527 commented on ex02/pokedex/src/components/PokeBallSpinner.vue
> +      <v-row>
ロード失敗時はクルクルを消した方がユーザフレンドりかと思います！

2021-01-21 13:17 UTC, dai65527 commented
修正後セルフマージしてください！笑

2021-01-21 14:53 UTC, merged